### ISSUE TITLE
Default Value Does not Work

### ISSUE THREAD

**Issue by elibroftw** [zikwall/use-localforage#3]
```jsx
const preferredColorScheme = 'dark';
const [colorScheme, setColorScheme] = useLocalForage(preferredColorScheme);
console.log(colorScheme === undefined);  // true???
```
I'm trying to use this module instead of my custom getItem, but the defaultValue does not work properly!
I also suspect this is what's causing https://mantine.dev/ to be in light mode for 1 second before turning dark.

**Comment by gormonn** [comment]
Hey! You forgot an key!
 useLocalForage<D>(key: string, initialValue: D, errorHandler?: ErrorHandler)
